
# on:
#   push:
#     branches: [main]


name: Run Selenium On GitHub Action
on:
  push:
    branches: [main]
  schedule:
  # Schedule this job because our time in IST and server time is UTC
    - cron: '30 4,14 * * *' # Schedule to run at 10 AM and 8 PM (UTC time)
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous Chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch requests if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Running the Python script
        env:
          LU: ${{ secrets.LU }}
          LP: ${{ secrets.LP }}
        run: |
          echo "Username: $LU"
          echo "password: $LP"
          echo ${{ secrets.LU }}
          echo ${{ secrets.LP }}
          python selenium_script.py
